///
/// @Generated by Mockolo
///



import Foundation


public class FooMock: Foo {
    public init() { }
    public init(num: Int = 0) {
        self.num = num
    }


    public private(set) var numSetCallCount = 0
    public var num: Int = 0 { didSet { numSetCallCount += 1 } }

    public private(set) var barCallCount = 0
    public var barHandler: ((Float) -> (String))?
    public func bar(arg: Float) -> String {
        barCallCount += 1
        if let barHandler = barHandler {
            return barHandler(arg)
        }
        return ""
    }
}

